 
name: 'Build and Deploy'
on:
  push:
    branches:
      - master
jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - {name: Auto Deploy, run: 'yarn run deploy'}
