 
name: 'Build and Deploy'
on:
  push:
    branches:
      - master
jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - {name: Print Structure, run: 'ls'}
      - {name: Print Structure, run: 'pwd'}
      - {name: NPM Version, run: 'npm --version'}
      - {name: Node Version, run: 'node --version'}
      - {name: Yarn Version, run: 'yarn --version'}
      - {name: Install Dependencies, run: 'yarn install'}
      - {name: Build and Deploy, run: 'yarn run deploy'}